spring:
 mail:
    host: smtp.gmail.com
    username: mkeerthish6@gmail.com
    password: kompiuasxbdgdlmu
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true